spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=movie_database;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true